# Generated by Django 5.0.1 on 2024-01-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('leftOrRight', models.CharField(choices=[('L', 'Left'), ('R', 'Right')], max_length=1)),
            ],
        ),
    ]
